version: '3.8'

services:
  web:
    build: .
    command: gunicorn redis_mandalorian_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    env_file:
      - .env

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A redis_mandalorian_project worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env
