# Generated by Django 5.2 on 2025-04-08 19:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('alquilado', 'Alquilado')], default='disponible', max_length=10)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('rented_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
